version: '2.2'

services:

# webserver + php config
  php:
    build: php
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - ./php/www:/var/www/html
    cpus: 1
    mem_limit: 1024m

# phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:db
    ports:
    
        - 8080:80
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: test123
    cpus: 1
    mem_limit: 1024m

# mysql database
  db:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - /var/lib/mysql
    restart: on-failure
    environment:
     - MYSQL_ROOT_PASSWORD=test123
     - MYSQL_DATABASE=database
    cpus: 1
    mem_limit: 1024m
